# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'ArtifactorySaaS'
    sourceRepo: 'alpha-npm-virtual'
    collectBuildInfo: true
    threads: '10'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

# - task: Npm@1
#   inputs:
#      command: 'install'
#   displayName: 'Download dependencies'

# - script: |
#     npm install
#   displayName: 'Download dependencies'

- script: |
    npm run build
  displayName: 'Build'

- script: |
    npm pack
  displayName: 'Build the package'

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'ArtifactorySaaS'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
              "files": [
                {
                  "pattern": "npm-example*",
                  "target": "alpha-npm-dev-local/"
                }
              ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    failNoOp: true

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'ArtifactorySaaS'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'ArtifactorySaaS'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false

- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'ArtifactorySaaS'
    buildName: '${Build.DefinitionName}' 
    buildNumber: '${Build.BuildNumber}'
    targetRepo: 'alpha-npm-virtual'
    status: 'Dev'
    includeDependencies: false
    copy: false
    dryRun: false

