
name: 'JFrog CI Integration'
on: [push]
jobs:
 jfrog-ci-integration:
   runs-on: ubuntu-latest
   env:
     JF_URL: ${{ secrets.JF_URL }}
     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
     JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup JFrog CLI
       uses: jfrog/frogbot@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
     - name: Build
       run: |
         # Configure the project
         jf rt npm-config --server-id-resolve jfrog-instance --repo-resolve alpha-npm-virtual
         # Build the project using JFrog CLI
         jf rt npmi
     - name: Failure check
       run: |
         echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
       if: failure()
     - name: Publish build
       run: |
         # Collect and store environment variables in the build-info
         jf rt bce
         # Collect and store VCS details in the build-info
         jf rt bag
         # Publish the build-info to Artifactory
         jf rt bp
         # Scan the published build-info with Xray
         jf rt bs
       if: always()
